package com.example.homework_2

import com.example.homework_2.datasource.MessageDatasource
import okhttp3.Credentials

const val USER_EMAIL = "iamsoalivenow@gmail.com"
const val API_KEY = "wKUjjObJDaru9ErHEf9ryU3yZ7NFvikA"
const val BASE_URL = "https://tinkoff-android-spring-2023.zulipchat.com/api/v1/"
val AUTH_KEY: String = Credentials.basic(USER_EMAIL, API_KEY)

object MessageTypes {
    const val SENDER = "sender"
    const val RECEIVER = "receiver"
    const val DATA_SEPARATOR = "data separator"
}

object Status {
    const val ACTIVE = "active"
    const val IDLE = "idle"
    const val OFFLINE = "offline"
}

val emojiSetNCS = listOf(
    MessageDatasource.EmojiNCS("grinning", "1f600"),
    MessageDatasource.EmojiNCS("smiley", "1f603"),
    MessageDatasource.EmojiNCS("big_smile", "1f604"),
    MessageDatasource.EmojiNCS("grinning_face_with_smiling_eyes", "1f601"),
    MessageDatasource.EmojiNCS("laughing", "1f606"),
    MessageDatasource.EmojiNCS("sweat_smile", "1f605"),
    MessageDatasource.EmojiNCS("rolling_on_the_floor_laughing", "1f923"),
    MessageDatasource.EmojiNCS("joy", "1f602"),
    MessageDatasource.EmojiNCS("smile", "1f642"),
    MessageDatasource.EmojiNCS("upside_down", "1f643"),
    MessageDatasource.EmojiNCS("wink", "1f609"),
    MessageDatasource.EmojiNCS("blush", "1f60a"),
    MessageDatasource.EmojiNCS("innocent", "1f607"),
    MessageDatasource.EmojiNCS("heart_eyes", "1f60d"),
    MessageDatasource.EmojiNCS("heart_kiss", "1f618"),
    MessageDatasource.EmojiNCS("kiss", "1f617"),
    MessageDatasource.EmojiNCS("smiling_face", "263a"),
    MessageDatasource.EmojiNCS("kiss_with_blush", "1f61a"),
    MessageDatasource.EmojiNCS("kiss_smiling_eyes", "1f619"),
    MessageDatasource.EmojiNCS("yum", "1f60b"),
    MessageDatasource.EmojiNCS("stuck_out_tongue", "1f61b"),
    MessageDatasource.EmojiNCS("stuck_out_tongue_wink", "1f61c"),
    MessageDatasource.EmojiNCS("stuck_out_tongue_closed_eyes", "1f61d"),
    MessageDatasource.EmojiNCS("money_face", "1f911"),
    MessageDatasource.EmojiNCS("hug", "1f917"),
    MessageDatasource.EmojiNCS("thinking", "1f914"),
    MessageDatasource.EmojiNCS("silence", "1f910"),
    MessageDatasource.EmojiNCS("neutral", "1f610"),
    MessageDatasource.EmojiNCS("expressionless", "1f611"),
    MessageDatasource.EmojiNCS("speechless", "1f636"),
    MessageDatasource.EmojiNCS("smirk", "1f60f"),
    MessageDatasource.EmojiNCS("unamused", "1f612"),
    MessageDatasource.EmojiNCS("rolling_eyes", "1f644"),
    MessageDatasource.EmojiNCS("grimacing", "1f62c"),
    MessageDatasource.EmojiNCS("lying", "1f925"),
    MessageDatasource.EmojiNCS("relieved", "1f60c"),
    MessageDatasource.EmojiNCS("pensive", "1f614"),
    MessageDatasource.EmojiNCS("sleepy", "1f62a"),
    MessageDatasource.EmojiNCS("drooling", "1f924"),
    MessageDatasource.EmojiNCS("sleeping", "1f634"),
    MessageDatasource.EmojiNCS("cant_talk", "1f637"),
    MessageDatasource.EmojiNCS("sick", "1f912"),
    MessageDatasource.EmojiNCS("hurt", "1f915"),
    MessageDatasource.EmojiNCS("nauseated", "1f922"),
    MessageDatasource.EmojiNCS("sneezing", "1f927"),
    MessageDatasource.EmojiNCS("dizzy", "1f635"),
    MessageDatasource.EmojiNCS("cowboy", "1f920"),
    MessageDatasource.EmojiNCS("sunglasses", "1f60e"),
    MessageDatasource.EmojiNCS("nerd", "1f913"),
    MessageDatasource.EmojiNCS("oh_no", "1f615"),
    MessageDatasource.EmojiNCS("worried", "1f61f"),
    MessageDatasource.EmojiNCS("frown", "1f641"),
    MessageDatasource.EmojiNCS("sad", "2639"),
    MessageDatasource.EmojiNCS("open_mouth", "1f62e"),
    MessageDatasource.EmojiNCS("hushed", "1f62f"),
    MessageDatasource.EmojiNCS("astonished", "1f632"),
    MessageDatasource.EmojiNCS("flushed", "1f633"),
    MessageDatasource.EmojiNCS("frowning", "1f626"),
    MessageDatasource.EmojiNCS("anguished", "1f627"),
    MessageDatasource.EmojiNCS("fear", "1f628"),
    MessageDatasource.EmojiNCS("cold_sweat", "1f630"),
    MessageDatasource.EmojiNCS("exhausted", "1f625"),
    MessageDatasource.EmojiNCS("cry", "1f622"),
    MessageDatasource.EmojiNCS("sob", "1f62d"),
    MessageDatasource.EmojiNCS("scream", "1f631"),
    MessageDatasource.EmojiNCS("confounded", "1f616"),
    MessageDatasource.EmojiNCS("persevere", "1f623"),
    MessageDatasource.EmojiNCS("disappointed", "1f61e"),
    MessageDatasource.EmojiNCS("sweat", "1f613"),
    MessageDatasource.EmojiNCS("weary", "1f629"),
    MessageDatasource.EmojiNCS("anguish", "1f62b"),
    MessageDatasource.EmojiNCS("triumph", "1f624"),
    MessageDatasource.EmojiNCS("rage", "1f621"),
    MessageDatasource.EmojiNCS("angry", "1f620"),
    MessageDatasource.EmojiNCS("smiling_devil", "1f608"),
    MessageDatasource.EmojiNCS("devil", "1f47f"),
    MessageDatasource.EmojiNCS("skull", "1f480"),
    MessageDatasource.EmojiNCS("skull_and_crossbones", "2620"),
    MessageDatasource.EmojiNCS("poop", "1f4a9"),
    MessageDatasource.EmojiNCS("clown", "1f921"),
    MessageDatasource.EmojiNCS("ogre", "1f479"),
    MessageDatasource.EmojiNCS("goblin", "1f47a"),
    MessageDatasource.EmojiNCS("ghost", "1f47b"),
    MessageDatasource.EmojiNCS("alien", "1f47d"),
    MessageDatasource.EmojiNCS("space_invader", "1f47e"),
    MessageDatasource.EmojiNCS("robot", "1f916"),
    MessageDatasource.EmojiNCS("smiley_cat", "1f63a"),
    MessageDatasource.EmojiNCS("smile_cat", "1f638"),
    MessageDatasource.EmojiNCS("joy_cat", "1f639"),
    MessageDatasource.EmojiNCS("heart_eyes_cat", "1f63b"),
    MessageDatasource.EmojiNCS("smirk_cat", "1f63c"),
    MessageDatasource.EmojiNCS("kissing_cat", "1f63d"),
    MessageDatasource.EmojiNCS("scream_cat", "1f640"),
    MessageDatasource.EmojiNCS("crying_cat", "1f63f"),
    MessageDatasource.EmojiNCS("angry_cat", "1f63e"),
    MessageDatasource.EmojiNCS("see_no_evil", "1f648"),
    MessageDatasource.EmojiNCS("hear_no_evil", "1f649"),
    MessageDatasource.EmojiNCS("speak_no_evil", "1f64a"),
    MessageDatasource.EmojiNCS("lipstick_kiss", "1f48b"),
    MessageDatasource.EmojiNCS("love_letter", "1f48c"),
    MessageDatasource.EmojiNCS("cupid", "1f498"),
    MessageDatasource.EmojiNCS("gift_heart", "1f49d"),
    MessageDatasource.EmojiNCS("sparkling_heart", "1f496"),
    MessageDatasource.EmojiNCS("heart_pulse", "1f497"),
    MessageDatasource.EmojiNCS("heartbeat", "1f493"),
    MessageDatasource.EmojiNCS("revolving_hearts", "1f49e"),
    MessageDatasource.EmojiNCS("two_hearts", "1f495"),
    MessageDatasource.EmojiNCS("heart_box", "1f49f"),
    MessageDatasource.EmojiNCS("heart_exclamation", "2763"),
    MessageDatasource.EmojiNCS("broken_heart", "1f494"),
    MessageDatasource.EmojiNCS("heart", "2764"),
    MessageDatasource.EmojiNCS("yellow_heart", "1f49b"),
    MessageDatasource.EmojiNCS("green_heart", "1f49a"),
    MessageDatasource.EmojiNCS("blue_heart", "1f499"),
    MessageDatasource.EmojiNCS("purple_heart", "1f49c"),
    MessageDatasource.EmojiNCS("black_heart", "1f5a4"),
    MessageDatasource.EmojiNCS("100", "1f4af"),
    MessageDatasource.EmojiNCS("anger", "1f4a2"),
    MessageDatasource.EmojiNCS("boom", "1f4a5"),
    MessageDatasource.EmojiNCS("seeing_stars", "1f4ab"),
    MessageDatasource.EmojiNCS("sweat_drops", "1f4a6"),
    MessageDatasource.EmojiNCS("dash", "1f4a8"),
    MessageDatasource.EmojiNCS("hole", "1f573"),
    MessageDatasource.EmojiNCS("bomb", "1f4a3"),
    MessageDatasource.EmojiNCS("umm", "1f4ac"),
    MessageDatasource.EmojiNCS("speech_bubble", "1f5e8"),
    MessageDatasource.EmojiNCS("anger_bubble", "1f5ef"),
    MessageDatasource.EmojiNCS("thought", "1f4ad"),
    MessageDatasource.EmojiNCS("zzz", "1f4a4"),
)

